import { createSlice } from "@reduxjs/toolkit";
import db from "../Database/index";
const initialState = db.profile;
const userProfileSlice = createSlice({
  name: "userProfile",
  initialState,
  reducers: {
    updateUserProfile: (state, action) => {
      return { ...state, ...action.payload };
    },
  },
});

// Export the actions generated by `createSlice`
export const { updateUserProfile } = userProfileSlice.actions;

// Export the reducer from the generated slice
export default userProfileSlice.reducer;
